on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.x

    - name: Run formatter and fail if not formatted
      run: |
        deno fmt --check || (echo "Code has not been formatted. May I suggest you install git hooks on your development machine?" && exit 1)

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.x

    - name: Run lint and fail if there are errors
      run: |
        deno lint || (echo "Lint errors found. Please fix the issues above." && exit 1)